[project]
name = "imc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "elasticdeform>=0.5.1",
    "gcs-torch-dataflux>=1.4.0",
    "google-cloud-storage>=3.4.1",
    "ipykernel>=7.0.1",
    "matplotlib>=3.10.6",
    "ml-dtypes>=0.4.1",
    "natsort>=8.4.0",
    "nibabel>=5.3.2",
    "numpy>2.1.0",
    "onnx==1.18.0",
    "onnxruntime>=1.23.2",
    "onnxruntime-gpu>=1.23.2",
    "onnxscript>=0.5.0",
    "pandas>=2.3.3",
    "pydicom>=3.0.1",
    "python-gdcm>3.0.10",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "tabulate>=0.9.0",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "torch-tb-profiler>=0.4.3",
    "torchvision>=0.23.0",
    "tqdm>=4.67.1",
]
[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "IMC"
module-root = "./"
